// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function SalesSummaryByDate(arg1:domain.DateArg,arg2:domain.DateArg):Promise<Array<domain.SaleSummary>>;

export function Start(arg1:context.Context):Promise<void>;
