// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {domain} from '../models';
import {context} from '../models';

export function OrdersMadeInAMonth(arg1:time.Time):Promise<Array<domain.Order>>;

export function OrdersSummaryByDate(arg1:domain.DateArg,arg2:domain.DateArg):Promise<Array<domain.Order>>;

export function Start(arg1:context.Context):Promise<void>;
