// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OrdersMadeInAMonth(arg1) {
  return window['go']['metrics']['Metrics']['OrdersMadeInAMonth'](arg1);
}

export function OrdersSummaryByDate(arg1, arg2) {
  return window['go']['metrics']['Metrics']['OrdersSummaryByDate'](arg1, arg2);
}

export function Start(arg1) {
  return window['go']['metrics']['Metrics']['Start'](arg1);
}
