// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dollar():Promise<number>;

export function Update(arg1:number):Promise<void>;
