// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dollar() {
  return window['go']['currency']['currency']['Dollar']();
}

export function Update(arg1) {
  return window['go']['currency']['currency']['Update'](arg1);
}
