// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function AddItemToCart(arg1:any):Promise<void>;

export function CreateCostumer(arg1:any):Promise<domain.Message>;

export function DeleteOrder(arg1:number):Promise<domain.Message>;

export function GetCartItems():Promise<Array<domain.OrderItemPayload>>;

export function GetCostumerById(arg1:number):Promise<domain.Costumer>;

export function GetCostumers():Promise<Array<domain.Costumer>>;

export function ListOrders():Promise<Array<domain.Order>>;

export function ListOrdersByDate(arg1:domain.DateArg):Promise<Array<domain.Order>>;

export function ListOrdersByDateRange(arg1:domain.DateArg,arg2:domain.DateArg):Promise<Array<domain.Order>>;

export function ListOrdersByStatus(arg1:string):Promise<Array<domain.Order>>;

export function MarkAsPaid(arg1:number,arg2:string):Promise<domain.Message>;

export function RemoveItemFromCart(arg1:number):Promise<void>;

export function ResetCart():Promise<void>;

export function SaveOrder(arg1:domain.OrderPayload):Promise<domain.Message>;

export function Start(arg1:context.Context):Promise<void>;
