// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItemToCart(arg1) {
  return window['go']['sales']['Sales']['AddItemToCart'](arg1);
}

export function CreateCostumer(arg1) {
  return window['go']['sales']['Sales']['CreateCostumer'](arg1);
}

export function GetCartItems() {
  return window['go']['sales']['Sales']['GetCartItems']();
}

export function GetCostumers() {
  return window['go']['sales']['Sales']['GetCostumers']();
}

export function ListOrders() {
  return window['go']['sales']['Sales']['ListOrders']();
}

export function ListOrdersByDate(arg1) {
  return window['go']['sales']['Sales']['ListOrdersByDate'](arg1);
}

export function ListOrdersByDateRange(arg1, arg2) {
  return window['go']['sales']['Sales']['ListOrdersByDateRange'](arg1, arg2);
}

export function RemoveItemFromCart(arg1) {
  return window['go']['sales']['Sales']['RemoveItemFromCart'](arg1);
}

export function ResetCart() {
  return window['go']['sales']['Sales']['ResetCart']();
}

export function SaveOrder(arg1) {
  return window['go']['sales']['Sales']['SaveOrder'](arg1);
}

export function Start(arg1) {
  return window['go']['sales']['Sales']['Start'](arg1);
}
