// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function AddItemToCart(arg1:any):Promise<void>;

export function GetCartItems():Promise<Array<domain.OrderItemPayload>>;

export function RemoveItemFromCart(arg1:number):Promise<void>;

export function ResetCart():Promise<void>;

export function Start(arg1:context.Context):Promise<void>;
