// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItemToCart(arg1) {
  return window['go']['sales']['Sales']['AddItemToCart'](arg1);
}

export function CreateCustomer(arg1) {
  return window['go']['sales']['Sales']['CreateCustomer'](arg1);
}

export function DeleteCustomer(arg1) {
  return window['go']['sales']['Sales']['DeleteCustomer'](arg1);
}

export function DeleteOrder(arg1) {
  return window['go']['sales']['Sales']['DeleteOrder'](arg1);
}

export function GetCartItems() {
  return window['go']['sales']['Sales']['GetCartItems']();
}

export function GetCustomerById(arg1) {
  return window['go']['sales']['Sales']['GetCustomerById'](arg1);
}

export function GetCustomers() {
  return window['go']['sales']['Sales']['GetCustomers']();
}

export function GetOrdersByCustomerAndStatus(arg1, arg2) {
  return window['go']['sales']['Sales']['GetOrdersByCustomerAndStatus'](arg1, arg2);
}

export function GetTotalPayments(arg1) {
  return window['go']['sales']['Sales']['GetTotalPayments'](arg1);
}

export function ListOrders() {
  return window['go']['sales']['Sales']['ListOrders']();
}

export function ListOrdersByDate(arg1) {
  return window['go']['sales']['Sales']['ListOrdersByDate'](arg1);
}

export function ListOrdersByDateRange(arg1, arg2) {
  return window['go']['sales']['Sales']['ListOrdersByDateRange'](arg1, arg2);
}

export function ListOrdersByStatus(arg1) {
  return window['go']['sales']['Sales']['ListOrdersByStatus'](arg1);
}

export function MakeAPartialPayment(arg1, arg2, arg3) {
  return window['go']['sales']['Sales']['MakeAPartialPayment'](arg1, arg2, arg3);
}

export function RemoveItemFromCart(arg1) {
  return window['go']['sales']['Sales']['RemoveItemFromCart'](arg1);
}

export function ResetCart() {
  return window['go']['sales']['Sales']['ResetCart']();
}

export function SaveOrder(arg1) {
  return window['go']['sales']['Sales']['SaveOrder'](arg1);
}

export function Start(arg1) {
  return window['go']['sales']['Sales']['Start'](arg1);
}
