// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCleaningProduct(arg1) {
  return window['go']['main']['App']['CreateCleaningProduct'](arg1);
}

export function DeleteProductById(arg1) {
  return window['go']['main']['App']['DeleteProductById'](arg1);
}

export function GetCleaningProductById(arg1) {
  return window['go']['main']['App']['GetCleaningProductById'](arg1);
}

export function GetCleaningProducts() {
  return window['go']['main']['App']['GetCleaningProducts']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UpdateCleaningProduct(arg1) {
  return window['go']['main']['App']['UpdateCleaningProduct'](arg1);
}
