// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateCleaningProduct(arg1:string,arg2:number,arg3:string):Promise<domain.Message>;

export function DeleteProductById(arg1:number):Promise<domain.Message>;

export function GetCleaningProducts():Promise<Array<domain.CleaningProduct>>;

export function Greet(arg1:string):Promise<string>;

export function SalesObj():Promise<Array<domain.OrderItem>>;
