// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateCleaningProduct(arg1:any):Promise<domain.Message>;

export function DeleteProductById(arg1:number):Promise<domain.Message>;

export function GetCleaningProductById(arg1:number):Promise<domain.Product>;

export function GetCleaningProducts():Promise<Array<domain.Product>>;

export function Greet(arg1:string):Promise<string>;

export function UpdateCleaningProduct(arg1:any):Promise<domain.Message>;
